# -*- Makefile -*-

gomincludedir := $(includedir)/gom-0/gom
gominclude_HEADERS :=				\
	include/gom/gomcamel.h			\
	include/gom/gomchardata.h		\
	include/gom/gomdoc.h			\
	include/gom/gomdom.h			\
	include/gom/gomelem.h			\
	include/gom/gomeventtargetinternal.h	\
	include/gom/gomevt.h			\
	include/gom/gomevttgt.h			\
	include/gom/gomgcmanaged.h		\
	include/gom/gomgcmanager.h		\
	include/gom/gomglist.h			\
	include/gom/gomjscontext.h		\
	include/gom/gomjsdocument.h		\
	include/gom/gomjsdomexception.h		\
	include/gom/gomjselement.h		\
	include/gom/gomjsevent.h		\
	include/gom/gomjseventexception.h	\
	include/gom/gomjseventlistener.h	\
	include/gom/gomjseventtarget.h		\
	include/gom/gomjsexception.h		\
	include/gom/gomjsgerrorexception.h	\
	include/gom/gomjskeyboardevent.h	\
	include/gom/gomjsmouseevent.h		\
	include/gom/gomjsnavigator.h		\
	include/gom/gomjsnode.h			\
	include/gom/gomjsobject.h		\
	include/gom/gomjsuievent.h		\
	include/gom/gomjswindow.h		\
	include/gom/gomjsxmlhttprequest.h	\
	include/gom/gomkeyboardevt.h		\
	include/gom/gomkeyidentifiers.h		\
	include/gom/gomlistenerlist.h		\
	include/gom/gommouseevt.h		\
	include/gom/gomnodeinternal.h		\
	include/gom/gomnoodle.h			\
	include/gom/gomobject.h			\
	include/gom/gomtxt.h			\
	include/gom/gomuievt.h			\
	include/gom/gomuriutils.h		\
	include/gom/gomvalue.h			\
	include/gom/gomwidget.h			\
	include/gom/gomxhr.h

