# -*- Makefile -*-

gomincludedir := $(includedir)/gom-0/gom
gominclude_HEADERS :=				\
	include/gom/gomdoc.h			\
	include/gom/gomdom.h			\
	include/gom/gomglist.h			\
	include/gom/gomjsdocument.h		\
	include/gom/gomjselement.h		\
	include/gom/gomjsobject.h		\
	include/gom/gomjsnode.h			\
	include/gom/gomjswindow.h		\
	include/gom/gomobject.h			\
	include/gom/gomvalue.h			\
	include/gom/gomwidget.h
