# -*- Makefile -*-

# xpgomincludedir := $(includedir)/gom-0/xpgom
# xpgominclude_HEADERS :=
noinst_HEADERS += xgDOMImplementation.hh
noinst_HEADERS += xgDocument.hh
noinst_HEADERS += xgNode.hh
noinst_HEADERS += xgObject.hh
