# -*- Makefile -*-

# xpgomincludedir := $(includedir)/gom-0/xpgom
# xpgominclude_HEADERS :=
noinst_HEADERS += include/xpgom/xgDOMImplementation.hh
noinst_HEADERS += include/xpgom/xgDocument.hh
noinst_HEADERS += include/xpgom/xgNode.hh
noinst_HEADERS += include/xpgom/xgObject.hh
