# -*- Makefile -*-

# xpgomincludedir := $(includedir)/gom-0/xpgom
# xpgominclude_HEADERS :=
noinst_HEADERS += include/xpgom/gomwrapped.hh
noinst_HEADERS += include/xpgom/gomwrappeddocument.hh
noinst_HEADERS += include/xpgom/gomwrappeddomimplementation.hh
noinst_HEADERS += include/xpgom/gomwrappedelement.hh
noinst_HEADERS += include/xpgom/gomwrappednode.hh
noinst_HEADERS += include/xpgom/xgDOMImplementation.hh
noinst_HEADERS += include/xpgom/xgDocument.hh
noinst_HEADERS += include/xpgom/xgElement.hh
noinst_HEADERS += include/xpgom/xgNode.hh
noinst_HEADERS += include/xpgom/xgWrapped.hh
