# -*- Makefile -*-

domincludedir := $(includedir)/gom-0/gom/dom
dominclude_HEADERS :=				   \
	include/gom/dom/gomattr.h		   \
	include/gom/dom/gomcdatasection.h	   \
	include/gom/dom/gomcharacterdata.h	   \
	include/gom/dom/gomcomment.h		   \
	include/gom/dom/gomdocument.h		   \
	include/gom/dom/gomdocumentfragment.h	   \
	include/gom/dom/gomdocumenttype.h	   \
	include/gom/dom/gomdomexception.h	   \
	include/gom/dom/gomdomimplementation.h	   \
	include/gom/dom/gomelement.h		   \
	include/gom/dom/gomentityreference.h	   \
	include/gom/dom/gomnamednodemap.h	   \
	include/gom/dom/gomnode.h		   \
	include/gom/dom/gomnodelist.h		   \
	include/gom/dom/gomnotation.h		   \
	include/gom/dom/gomprocessinginstruction.h \
	include/gom/dom/gomtext.h
