# -*- Makefile -*-

dist_noinst_DATA += idl/xgPIWrapped.idl
dist_noinst_DATA += idl/xgIParser.idl
dist_noinst_DATA += idl/xgIWindow.idl

noinst_DATA += idl/xgPIWrapped.xpt
noinst_DATA += idl/xgIParser.xpt
noinst_DATA += idl/xgIWindow.xpt
