#include "nsISupports.idl"

interface nsIDOMDocument;

[scriptable, uuid(194C04B0-62FD-4594-822D-1CDB3596BB7C)]
interface xgIGomParserListener : nsISupports
{
    void documentCreated (in nsIDOMDocument document);
};

[scriptable, uuid(5B251DFE-C380-4298-B547-11A006AB4784)]
interface xgIGomParser : nsISupports
{
    nsIDOMDocument parseURI (in string uri, in xgIGomParserListener listener);
};
